import type { Metadata } from "next";

import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


export const metadata: Metadata = {
  title: "Football Feeds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="w-full max-w-6xl mx-auto">
          {/* Navbar */}
          <div className="">
            <Navbar />
          </div>

          {/* Main content */}
          <main>{children}</main>

          {/* Footer */}
          <div className="w-full max-w-6xl mx-auto">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
